name: Add Grafana Dashboard

on:
  push:
    branches:
      - master

jobs:
  add_dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Grafana API client
        run: pip install -U grafana_api_client

      - name: Load xml file
        id: dashboard
        uses: actions/download-artifact@v2
        with:
          name: my-dashboard
          path: unit-test/build/report.xml

      - name: Add Dashboard
        uses: naveen1902/unit-test-action@v0.2.0
        with:
          url:  http://100.20.0.129:3000/
          api_key: eyJrIjoidldHRHRTTmZhaDc3cWJDOTJnNlFYRGZyZEFUZXZNYjAiLCJuIjoiZ2l0YWN0IiwiaWQiOjF9
          dashboard: http://100.20.0.129:3000/d/7doGbax4z/gitactions?orgId=1
