name: Publish Test Reports to Grafana Dashboard

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Test Reports
        uses: naveen1902/unit-test-upload-action@v1
        with:
          dashboard_url: ${{ http://100.20.0.129:3000 }}
          api_key: ${{ eyJrIjoidlZ4ajhvQlRLZWVHNFVZelp0TTVIakxVeVVOTmt4M1QiLCJuIjoibmV3a2V5IiwiaWQiOjF9 }}
          file_path: 'unit-tests/build/report.xml'
