name: Publish Test Reports to Grafana Dashboard

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Test Reports
        uses: brianchristensen/grafana-dashboard-upload-action@v1
        with:
          dashboard_url: ${{ secrets.DASHBOARD_URL }}
          api_key: ${{ secrets.API_KEY }}
          file_path: './test-reports/results.json'
