name: Send XML file to Grafana Dashboard

on:
  push:
    branches: [ master ]

jobs:
  send-to-grafana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone a tata-project repo
        uses: actions/checkout@v3
        with:
          repository: naveen1902/unit-test
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          #token: ${{ secrets.BG_POLARIS }}
          path: unit-test
          
          
          
      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl
        
      - name: Publish dashboard to Grafana
        uses: codecentric/grafana-dashboard-publish-action@v1.0.1
        with:
          grafana-url: ${{ http://100.20.0.129:3000 }}
          grafana-api-key: ${{ eyJrIjoidldHRHRTTmZhaDc3cWJDOTJnNlFYRGZyZEFUZXZNYjAiLCJuIjoiZ2l0YWN0IiwiaWQiOjF9 }}
          dashboard-json-file-path: http://100.20.0.129:3000/dashboards/f/t4mLWRa4k/reports
          overwrite: true



      - name: Send to Grafana
        run: |
          curl -X POST \
            -H "Content-Type: application/xml" \
            -H "Authorization: Bearer eyJrIjoidldHRHRTTmZhaDc3cWJDOTJnNlFYRGZyZEFUZXZNYjAiLCJuIjoiZ2l0YWN0IiwiaWQiOjF9" \
            -d "@unit-tests/build/report.xml"\
             http://100.20.0.129:3000/dashboards/f/t4mLWRa4k/reports?query=
